name: Generate KiCad Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create output directory
      run: mkdir -p kicad_docs

    - name: Export schematic PDF
      run: |
        docker run --rm -v $(pwd):/workdir kicad/kicad:8.0.3 /bin/bash -c "
          mkdir -p /workdir/kicad_docs &&
          kicad-cli sch export pdf -o /workdir/kicad_docs/schematic.pdf /workdir/hardware-electronics/M2SmartHome.kicad_sch || true
        "

    - name: Export PCB PDF
      run: |
        docker run --rm -v $(pwd):/workdir kicad/kicad:8.0.3 /bin/bash -c "
          mkdir -p /workdir/kicad_docs &&
          kicad-cli pcb export pdf --layers F.Cu,B.Cu,Edge.Cuts -o /workdir/kicad_docs/pcb.pdf /workdir/hardware-electronics/M2SmartHome.kicad_pcb || true
        "

    - name: Export STEP file
      run: |
        docker run --rm -v $(pwd):/workdir kicad/kicad:8.0.3 /bin/bash -c "
          mkdir -p /workdir/kicad_docs &&
          kicad-cli pcb export step -o /workdir/kicad_docs/board.step /workdir/hardware-electronics/M2SmartHome.kicad_pcb || true
        "

    - name: List output files
      run: ls -la kicad_docs

    - name: Upload PDF Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kicad-docs
        path: kicad_docs/*
