name: "Kicad 8 release CI"

on:
  workflow_dispatch:

jobs:
  call-export:
    uses: lukasznowarkiewicz/kicadReleaseCI/.github/workflows/kicad_export.yml@main
    with:
      target_repo: ${{ github.repository }}
      target_ref: ${{ github.ref }}
